### PR TITLE
Fixed references

### LINKED ISSUE #13: Missing references
In section 4, [line 1321 (of VOEvent.tex)](https://github.com/ivoa-std/VOEvent/blob/master/VOEvent.tex#L1321), the VODataService reference is missing. 

Same section, the reference to the Kafka reference is also missing ([line 1379 of VOEvent.tex](https://github.com/ivoa-std/VOEvent/blob/master/VOEvent.tex#L1379))

And later, the reference to RegTAP is not displayed either ([line 1418 of VOEvent.tex](https://github.com/ivoa-std/VOEvent/blob/master/VOEvent.tex#L1418))

### PR DESCRIPTION
**Pull request by BaptisteCecconi**
This PR fixes #13

### CODE REVIEW

**Comment by BaptisteCecconi** [comment]
The new commits update the Kafka reference.

**Comment by molinaro-m** [comment]
Hi, silly thing: wouldn't it be possible to move to docrepo.bib references directly, rather than using the localrepo.bib?
(non-blocking, of course)

**Comment by BaptisteCecconi** [comment]
For references to IVOA documents, I agree, for other non-IVOA references, I don't think that would be the plan.

**Comment by molinaro-m** [comment]
> For references to IVOA documents, I agree, for other non-IVOA references, I don't think that would be the plan.

Yes, sorry, of course I meant for IVOA documents.

**Comment by jd-au** [comment]
Did you want to merge this PR as is or is the plan still to use IVOATex docrepo.bib in this PR?

**Review by jd-au — APPROVED** [review]

**Review by Zarquan — APPROVED** [review]
Looks good :+1:

**Pull request merged**
