### PR TITLE
Updating role diagram to use ivoatex/SVG

### PR DESCRIPTION
**Pull request by msdemlei**
This basically reflects what the old role diagram said, except I've taken out
all the standards that never came to be, and I've added VTP.

Followup changes should probably made to the section on the relationship
to the other standards, but I'm too far removed from VOEvent to dare doing
this.

### CODE REVIEW

**Comment by BaptisteCecconi** [comment]
Didi you check PR #2 ? I updated the role diagram too.

**Comment by Zarquan** [comment]
> Didi you check PR #2 ? I updated the role diagram too.

I merged PR #2, so is this needed now ?

**Comment by BaptisteCecconi** [comment]
I've fixed the merge conflicts in `role_diagram.xml`

**Comment by BaptisteCecconi** [comment]
@Zarquan can you check and eventually approve ?

**Pull request merged**
